-- CreateTable
CREATE TABLE `TrainingApplication` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `fullName` VARCHAR(191) NOT NULL,
    `phone` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NULL,
    `selectedCourse` ENUM('COMPUTER_FOUNDATIONS', 'MICROSOFT_OFFICE', 'GOOGLE_TOOLS', 'E_GOVERNMENT_TOOLS', 'DIGITAL_CONTENT_CREATION', 'GRAPHIC_DESIGN', 'AI_AND_DIGITAL_TOOLS', 'BASIC_PROGRAMMING') NOT NULL,
    `preferredSchedule` VARCHAR(191) NULL,
    `experienceLevel` ENUM('BEGINNER', 'INTERMEDIATE') NOT NULL DEFAULT 'BEGINNER',
    `status` ENUM('PENDING', 'ACCEPTED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
